#!/usr/bin/python3

import os
import multiprocessing
import random
import subprocess
import sys
import taglib
import time

from itertools import cycle
from mpg123 import Mpg123, Out123

musicDir = "/home/loidor/.radiofeed/music/"
metadataFile = "/home/loidor/.radiofeed/metadata"

def playlistGenerator():
    playlist = os.listdir(musicDir)
    random.shuffle(playlist)
    return playlist

def player():
    while True:
        # Generate a playlist
        playlist = playlistGenerator()

        # Select metadataFile, create mp3 player
        out = Out123()

        # Iterate through playlist, get metadata to metadataFile, play song
        for songName in playlist:
            song = musicDir + songName
            metadata = taglib.File(song)
            try:
            	artist = metadata.tags["ARTIST"]
            except:
                artist = ["[UNKNOWN ARTIST]"]
            try:
                title = metadata.tags["TITLE"]
            except:
                title = ["[UNKNOWN TITLE]"]
            metaOut = artist[0]+"\n"+title[0]+"\n"
            print("Now playing: " + songName)
            with open(metadataFile, "w") as file:
                file.write(metaOut)
            for frame in Mpg123(song).iter_frames(out.start):
                try:
                    out.play(frame)
                except:
                    print("Something effed up.")
                    continue

def streamer():

    while True:
        try:
            print(subprocess.check_output(['bash', '/opt/radiofeed/streamer']))
        except subprocess.CalledProcessError as err:
            print("ffmpeg hickup'd :(")
            time.sleep(5)
            continue

if __name__ == "__main__":
    p1 = multiprocessing.Process(target=player)
    p2 = multiprocessing.Process(target=streamer)

    p1.start()
    p2.start()
