#!/usr/bin/python3

import os
import multiprocessing
import random
import subprocess
import sys
import taglib
import time

from itertools import cycle
from mpg123 import Mpg123, Out123

music_dir = "/home/loidor/.radiofeed/music/"
music_base = '/home/loidor/.radiofeed/'
metadata_file = "/home/loidor/.radiofeed/metadata"
error_log = "error.log"

gif_dir="/home/loidor/.radiofeed/gifs/"

ffmpeg="/usr/local/bin/ffmpeg"
url="rtmp://192.168.1.2/hls/1"

filelist = []

def font_generator():
    fontlist = ['tanugo.ttf', 'yuseimagic.ttf', 'zenjido.ttf']
    random.shuffle(fontlist)
    return fontlist[0]

def playlist_generator():
    playlist = []
    for root, subdirs, files in os.walk(music_dir):
        for file in files:
            playlist.append(root + "/" + file)
    random.shuffle(playlist)
    return playlist

def gif_generator():
    giflist = os.listdir(gif_dir)
    random.shuffle(giflist)
    gif = gif_dir + giflist[0]
    return gif

def main():
    while True:
        # Generate a playlist
        playlist = playlist_generator()

        # Select metadataFile, create mp3 player
        out = Out123()

        # Iterate through playlist, get metadata to metadataFile, play song
        for song in playlist:
            # Generate a gif to loop
            gif = gif_generator()
            font = font_generator()

            streamer = subprocess.Popen([ffmpeg,
                             "-loglevel", "warning",
                             "-guess_layout_max", "0",
                             "-thread_queue_size", "32768",
                             "-f", "alsa" , "-ac", "2", 
                             "-i", "hw:Loopback,1,0",
                             "-fflags", "+genpts",
                             "-ignore_loop", "0",
                             "-i", gif,
                             "-vf", "scale=720:480:force_original_aspect_ratio=decrease,pad=720:480:(ow-iw)/2:(oh-ih)/2,setsar=1,drawtext=fontfile=/opt/radiofeed/" + font + ": fontcolor=0xFFFFFF: fontsize=32: shadowcolor=0x000000: shadowx=2: shadowy=2: x=15: y=375: reload=1: textfile= " + metadata_file,
                             "-c:v", "h264_omx",
                             "-b:v", "2500k",
                             "-c:a", "libfdk_aac",
                             "-b:a", "128k",
                             "-ar",  "48000",
                             "-f", "flv", url])

            metadata = taglib.File(song)
            try:
            	artist = metadata.tags["ARTIST"]
            except:
                artist = ["[UNKNOWN ARTIST]"]
            try:
                title = metadata.tags["TITLE"]
            except:
                title = ["[UNKNOWN TITLE]"]
            time.sleep(1)
            meta_out = artist[0]+"\n"+title[0]+"\n"
            print("Now playing: " + artist[0] + " - " + title[0])
            with open(metadata_file, "w") as file:
                file.write(meta_out)
            for frame in Mpg123(song).iter_frames(out.start):
                try:
                    out.play(frame)
                except:
                    print("Something effed up.")
                    break
            streamer.terminate()
            time.sleep(1)

if __name__ == "__main__":
    main()
