#!/bin/bash

shopt -s nullglob

GIFLIST=(/home/loidor/.radiofeed/gifs/*)

FFMPEG=/usr/local/bin/ffmpeg
#GIF=/home/loidor/.radiofeed/gifs/nge1.gif
GIF=${GIFLIST[$RANDOM % ${#GIFLIST[@]}]}
URL=rtmp://192.168.1.2/hls/1
FPS=7
TEXT=/home/loidor/.radiofeed/metadata


touch "$TEXT"

$FFMPEG -loglevel warning -guess_layout_max 0 \
-thread_queue_size 32768 \
-f alsa -ac 2 -i hw:Loopback,1,0 -fflags +genpts -ignore_loop 0 -r $FPS -i $GIF \
-vf  drawtext="fontfile=/opt/radiofeed/yuseimagic.ttf: fontcolor=0xFFFFFF: fontsize=24: shadowcolor=0x000000: shadowx=2: shadowy=2: x=10: y=10: reload=1: textfile=$TEXT" \
-c:v h264_omx \
-c:a libfdk_aac -b:a 128k -ar 48000 \
-f flv $URL
